### ISSUE TITLE
Support Unicode in adding events to buffer

### ISSUE THREAD

**Issue by juliemacdonell** [snowplow/snowplow-python-tracker#162]
See https://github.com/snowplow/snowplow-python-tracker/blob/master/snowplow_tracker/emitters.py#L142:

```
if self.method == "post":
    self.buffer.append({key: str(payload[key]) for key in payload})
else:
    self.buffer.append(payload)
```

Casting values in payload dict to strings raises UnicodeDecodeError when value is unicode string. Simple fix could be:

```
if self.method == "post":
    self.buffer.append({key: str(payload[key]) for key in payload if not isinstance(payload[key], unicode)})
else:
    self.buffer.append(payload)
```

**Comment by alexanderdean** [comment]
Thanks for raising @juliemacdonell!

**Comment by fblundun** [comment]
Thanks for pointing this out @juliemacdonell. I assume you are using Python 2? I can't reproduce this in Python 3.

It seems that in Python 2, it is possible to send Unicode in the parameters of a GET request, but putting it in the body of a POST request causes problems:

```
>>> requests.get('http://localhost:8900',params={"a":u'\xeab'})
<Response [200]>
>>> requests.post('http://localhost:8900',data=u'{"a":"\xeab"}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 562, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 839, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 811, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 6: ordinal not in range(128)
```

Rather than excluding the unicode strings from the POST body completely, we should find a way to send them in the body without the above exception.

**Comment by fblundun** [comment]
Looks like specifying the encoding as utf-8 prevents this error:

```
>>> requests.post('http://localhost:8900',data=u'{"a":"\xeab"}'.encode('utf-8'))
<Response [200]>
```

**Comment by juliemacdonell** [comment]
Ah whoops, bad fix on my part-- meant to cast as string if not type unicode, not exclude ;-)  Yes, we are working in Python 2.  Will give the encoding as utf-8 a try...thanks!
